import {chromium} from 'playwright';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),report=[],errors=[];
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{let rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(rel.endsWith('/'))rel+='index.html';const f=path.join(root,rel);if(!f.startsWith(root)||!fs.existsSync(f)){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res);});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({headless:true,...(process.env.ORBISV_CHROMIUM?{executablePath:process.env.ORBISV_CHROMIUM}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
async function test(name,fn){try{await fn();report.push({name,ok:true});}catch(e){report.push({name,ok:false,error:e.message});}}
const go=async id=>{await page.goto(url+'#laboratorio/'+id);await page.locator('#wbForm').waitFor();};
const calc=async()=>{await page.locator('#wbCalculate').click();await page.locator('#wbRecord').waitFor({timeout:15000});};
try{
await page.goto(url);await page.waitForFunction(()=>window.OrbisPlatform&&window.OrbisWorkbench);
await test('Catálogo: cinco áreas e 93 laboratórios',async()=>{assert.equal(await page.locator('.platform-area-card').count(),5);assert.equal(await page.evaluate(()=>Object.keys(OrbisCatalog.labs).length),93);});
await test('Busca sem acento e filtro por grupo',async()=>{await page.goto(url+'#area/calculo-2');await page.locator('#platformLabSearch').fill('primitivas');assert.equal(await page.locator('.platform-lab-card:visible').count(),1);await page.locator('#platformLabSearch').fill('');await page.locator('#platformGroupFilter').selectOption('Várias variáveis');assert.equal(await page.locator('.platform-lab-card:visible').count(),12);});
const ids=await page.evaluate(()=>LabKit.modules.map(m=>m.id));
for(const id of ids)await test('Worker e resultado: '+id,async()=>{await go(id);await calc();assert.equal(await page.locator('#wbStatus.error').count(),0);});
await test('Treino oculta resultados, aceita fração e registra resposta',async()=>{await go('fund-fracoes');await page.locator('#wbPractice').check();await page.locator('#wbCalculate').click();await page.locator('#wbGuess').waitFor();assert.equal(await page.locator('.wb-metrics').count(),0);await page.locator('#wbGuess').fill('3/2');await page.locator('#wbCheck').click();assert.match(await page.locator('#wbFeedback').innerText(),/dentro/);await page.locator('#wbReveal').click();await page.locator('#wbRecord').click();await page.locator('#platformNoteText').waitFor();assert.match(await page.locator('#platformNoteText').inputValue(),/3\/2/);});
await test('Anotação e experimento sobrevivem ao recarregamento',async()=>{await page.locator('#platformNoteTitle').fill('Experimento auditado');await page.locator('#platformNoteText').fill('Minha hipótese e meus cálculos.');await page.reload();await page.locator('#platformNoteTitle').waitFor();assert.equal(await page.locator('#platformNoteTitle').inputValue(),'Experimento auditado');assert.equal(await page.locator('#platformNoteText').inputValue(),'Minha hipótese e meus cálculos.');await page.locator('[data-note-restore]').click();await page.locator('#wb-a').waitFor();assert.equal(await page.locator('#wb-a').inputValue(),'2/3');});
await test('Edição invalida resultado e mantém entradas isoladas',async()=>{await calc();await page.locator('#wb-a').fill('7/8');assert.equal(await page.locator('#wbRecord').count(),0);await go('fund-expressoes');await go('fund-fracoes');assert.equal(await page.locator('#wb-a').inputValue(),'7/8');});
await test('Entrada inválida gera mensagem e libera formulário',async()=>{await page.locator('#wb-b').fill('0');await page.locator('#wb-op').selectOption('/');await page.locator('#wbCalculate').click();await page.locator('#wbStatus.error').waitFor();assert.match(await page.locator('#wbStatus').innerText(),/zero/);assert.equal(await page.locator('#wbCalculate').isDisabled(),false);});
await test('Exportações JSON, CSV e SVG do laboratório',async()=>{await go('calc1-derivacao');await calc();for(const [selector,ext] of [['#wbJson','.json'],['#wbCsv','.csv'],['#wbSvg','.svg']]){const pending=page.waitForEvent('download');await page.locator(selector).click();const d=await pending;assert.ok(d.suggestedFilename().endsWith(ext));assert.equal(await d.failure(),null);}});
await test('Caderno: importação inválida preserva notas',async()=>{await page.goto(url+'#caderno');const before=await page.evaluate(()=>OrbisPlatform.data().notes.length);await page.locator('#platformNotebookImport').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"format":"orbisv-platform","version":1,"notes":[{"title":"bad","text":"x","snapshot":{"kind":"calculation","labId":"missing","result":{}}}]}')});await page.locator('#platformStatus.error').waitFor();assert.equal(await page.evaluate(()=>OrbisPlatform.data().notes.length),before);});
await test('Caderno: exportação e reimportação sem duplicatas',async()=>{const wait=page.waitForEvent('download');await page.locator('[data-note-export]').click();const d=await wait,file=await d.path(),before=await page.evaluate(()=>OrbisPlatform.data().notes.length);await page.locator('#platformNotebookImport').setInputFiles(file);await page.waitForFunction(()=>document.getElementById('platformStatus').textContent.includes('adicionada'));assert.equal(await page.evaluate(()=>OrbisPlatform.data().notes.length),before);});
await test('Editor nativo: criação, edição, desfazer e registro',async()=>{await page.goto(url+'#laboratorio/fund-funcoes');await page.waitForFunction(()=>document.body.classList.contains('platform-editor-open'));await page.evaluate(()=>{const u=OrbisVRuntime.AppUI;u.drafts.function.expression='x^2';u.submitCurrent();});assert.equal(await page.evaluate(()=>OrbisVRuntime.objects.items.length),1);await page.evaluate(()=>{const r=OrbisVRuntime;r.AppUI.beginEdit(r.objects.items[0]);r.AppUI.drafts.function.expression='x^3';r.AppUI.submitCurrent();r.AppUI.undo();});assert.equal(await page.evaluate(()=>OrbisVRuntime.objects.items[0].data.expression),'x^2');await page.locator('[data-platform-record]').click();await page.locator('#platformNoteText').waitFor();assert.equal(await page.evaluate(()=>OrbisPlatform.data().notes[0].snapshot.kind),'scene');});
await test('Sessão gráfica conservada após cálculo específico',async()=>{await go('calc2-triplas');await calc();await page.goto(url+'#laboratorio/fund-funcoes');assert.equal(await page.evaluate(()=>OrbisVRuntime.objects.items[0].data.expression),'x^2');});
await test('12 práticas nativas abrem com modos válidos',async()=>{const ids=await page.evaluate(()=>Object.values(OrbisCatalog.labs).filter(l=>l.kind==='scene').map(l=>l.id));for(const id of ids){await page.goto(url+'#laboratorio/'+id);await page.waitForFunction(id=>document.getElementById('platformLabTitle').textContent===OrbisCatalog.labs[id].title,id);assert.ok(await page.evaluate(()=>OrbisVRuntime.AppUI.activeMode));}});
await test('Gráfico 3D gira e exporta desenho vetorial',async()=>{await go('geo-quadricas');await calc();const before=await page.locator('#wbPlot').innerHTML();await page.locator('#wbYaw').fill('60');await page.locator('#wbYaw').dispatchEvent('input');assert.notEqual(await page.locator('#wbPlot').innerHTML(),before);});
await test('Mobile claro: sem estouro horizontal, cálculo e Caderno',async()=>{await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.documentElement.dataset.theme='light');await go('calc2-quadratura');await calc();assert.ok(await page.evaluate(()=>document.getElementById('platformHub').scrollWidth<=innerWidth+2));await page.screenshot({path:path.join(root,'tests','mobile.png'),fullPage:true});await page.locator('#wbRecord').click();await page.locator('#platformNoteText').waitFor();assert.ok(await page.evaluate(()=>document.getElementById('platformHub').scrollWidth<=innerWidth+2));});
await test('Tema escuro e filtros de visão de cores',async()=>{await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await go('calc2-duplas');await calc();for(const mode of ['protanopia','deuteranopia','tritanopia','achromatopsia']){await page.evaluate(v=>document.documentElement.dataset.colorVision=v,mode);assert.ok((await page.locator('#platformHub').evaluate(e=>getComputedStyle(e).filter)).includes(mode));}await page.evaluate(()=>document.documentElement.dataset.colorVision='normal');await page.screenshot({path:path.join(root,'tests','desktop.png'),fullPage:true});});
await test('Offline: shell, módulos e cálculo sem conexão',async()=>{const offline=await browser.newContext({serviceWorkers:'allow'}),p=await offline.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>!!navigator.serviceWorker.controller);await offline.setOffline(true);await p.reload();await p.waitForFunction(()=>window.OrbisPlatform);await p.goto(url+'#laboratorio/calc2-quadratura');await p.locator('#wbCalculate').click();await p.locator('#wbRecord').waitFor({timeout:15000});await offline.close();});
await test('Abertura por arquivo local com Worker independente',async()=>{const c=await browser.newContext({serviceWorkers:'block'}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+path.join(root,'index.html')+'#laboratorio/fund-fracoes');await p.locator('#wbCalculate').click();await p.locator('#wbRecord').waitFor({timeout:15000});assert.match(await p.locator('.wb-metrics').innerText(),/3\/2/);await c.close();});
await test('Sem erros JavaScript não tratados',async()=>assert.deepEqual(errors,[]));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
const failed=report.filter(r=>!r.ok);fs.writeFileSync(path.join(root,'tests','browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({total:report.length,passed:report.length-failed.length,failures:failed},null,2));if(failed.length)process.exitCode=1;
