'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),ctx={console};ctx.window=ctx;vm.createContext(ctx);
for(const file of ['mathEngine.js','vendor/nerdamer-1.1.13.min.js',...['kernel','fundamentals','geometry','vectors','calculus1','calculus2','multivariable'].map(x=>'labs/'+x+'.js')])vm.runInContext(fs.readFileSync(path.join(root,'js',file),'utf8'),ctx,{filename:file});
const K=ctx.LabKit,run=(id,p={})=>{ctx.testId=id;ctx.testParams=p;return vm.runInContext('LabKit.run(testId,testParams)',ctx,{timeout:8000});},val=(r,label)=>r.metrics.find(m=>m.label===label)?.value;
const near=(v,expected,tol=1e-7)=>assert.ok(Number.isFinite(v)&&Math.abs(v-expected)<=tol*Math.max(1,Math.abs(expected)),`${v} ≠ ${expected}`);
const report=[];function test(name,fn){try{fn();report.push({name,ok:true});}catch(e){report.push({name,ok:false,error:e.message});}}
for(const module of K.modules)test('Exemplo: '+module.id,()=>{const r=run(module.id);assert.ok(Array.isArray(r.metrics));r.metrics.forEach(m=>{if(typeof m.value==='number')assert.ok(Number.isFinite(m.value));});});
test('Frações exatas e sinais',()=>{assert.equal(val(run('fund-fracoes',{a:'-1/2',b:'1/3',op:'+'}),'Fração irredutível'),'-1/6');assert.equal(val(run('fund-fracoes',{a:'2/3',b:'4/9',op:'/'}),'Fração irredutível'),'3/2');});
test('MDC e MMC de coprimos grandes',()=>{const r=run('fund-divisibilidade',{a:'99999989',b:'99999931'});near(val(r,'MDC'),1);assert.equal(val(r,'MMC exato'),String(99999989n*99999931n));});
test('Temperatura e unidades de volume',()=>{near(run('fund-unidades',{x:'32',from:'f',to:'c'}).primary,0);near(run('fund-unidades',{x:'1',from:'m3',to:'l'}).primary,1000);});
test('Implicação: contraposição e falácia',()=>{assert.equal(val(run('fund-logica'),'Classificação'),'Tautologia');assert.equal(val(run('fund-logica',{e:'(p -> q) <-> (q -> p)'}),'Classificação'),'Contingência');});
test('Inequação constante impossível e raiz dupla',()=>{assert.equal(val(run('fund-inequacoes',{a:'0',b:'0',c:'1',op:'lt'}),'Conjunto solução'),'∅');assert.equal(val(run('fund-inequacoes',{a:'1',b:'0',c:'0',op:'le'}),'Conjunto solução'),'{0}');});
test('Equação com raiz múltipla não na malha',()=>{const r=run('fund-equacoes',{e:'(x-0.123)^2'});assert.ok(r.rows.some(row=>Math.abs(row[0]-.123)<1e-7));});
test('Triângulo 3–4–5',()=>near(run('fund-triangulos').primary,6));
test('Operação complexa divisão',()=>{const r=run('fund-complexos',{a:'1;2',b:'1;-2',op:'/'});near(val(r,'Parte real'),-.6);near(val(r,'Parte imaginária'),.8);});
test('Probabilidades binomiais somam um',()=>{const r=run('fund-combinatoria',{n:'40',k:'10',p:'.3'});near(r.rows.reduce((s,row)=>s+row[1],0),1);});
test('Estatística amostral',()=>{const r=run('fund-estatistica',{data:'1;2;3'});near(val(r,'Média'),2);near(val(r,'Variância amostral'),1);});
test('Interseção de planos satisfaz ambas as equações',()=>{const r=run('geo-planos');assert.equal(val(r,'Ponto da interseção'),'0,3333333333; 1,666666667; 1,333333333');});
test('Circunferência tangente tem um ponto',()=>{const r=run('geo-circunferencia',{c:'0;0',r:'3',line:'1;0;-3'});assert.equal(r.rows.length,1);near(r.rows[0][0],3);});
test('Cônicas reais e imaginárias',()=>{assert.equal(val(run('geo-conica-geral',{coef:'1;0;1;0;0;1'}),'Classificação'),'Elipse imaginária (sem pontos reais)');near(val(run('geo-conicas',{shape:'hyperbola',a:'3',b:'4'}),'Excentricidade'),5/3);});
test('Esféricas no equador',()=>{const r=run('geo-coordenadas',{type:'sph',p:'2;0;pi/2'});near(val(r,'r'),2);near(val(r,'ρ'),2);});
test('Inversa de matriz verificada por produto',()=>{const a=[[4,7],[2,6]],inv=K.inverse(a),product=K.multiply(a,inv);product.forEach((r,i)=>r.forEach((v,j)=>near(v,+(i===j))));});
test('Sistema incompatível e indeterminado',()=>{assert.equal(val(run('alg-sistemas',{a:'1;1\n2;2',b:'1;3'}),'Classificação'),'Incompatível');assert.equal(val(run('alg-sistemas',{a:'1;1\n2;2',b:'1;2'}),'Classificação'),'Infinitas soluções');});
test('Núcleo satisfaz Av=0',()=>{const r=run('alg-bases');r.rows.forEach(v=>[[1,0,1],[0,1,1],[0,0,0]].forEach(a=>near(K.dot(a,v),0)));});
test('Gram–Schmidt ortonormal',()=>{const r=run('alg-gram-schmidt');r.rows.forEach((v,i)=>r.rows.forEach((w,j)=>near(K.dot(v,w),+(i===j))));});
test('Produto vetorial perpendicular aos fatores',()=>{const u=[1,2,3],v=[-1,4,2],w=K.cross(u,v);near(K.dot(u,w),0);near(K.dot(v,w),0);});
test('Autovalores complexos da rotação',()=>{const r=run('alg-autovalores',{a:'0;-1\n1;0'});assert.ok(val(r,'λ₁').includes('1i'));});
test('Regressão recupera reta exata',()=>{const r=run('alg-minimos-quadrados',{data:'0;2\n1;5\n3;11'});near(val(r,'Coeficiente a'),3);near(val(r,'Coeficiente b'),2);near(val(r,'R²'),1);});
test('Limites: lados opostos de 1/x não são somados',()=>{const r=run('calc1-aproximacoes',{f:'1/x',c:'0'});assert.ok(r.rows.at(-1)[1]<0&&r.rows.at(-1)[3]>0);});
test('Derivada de log base 10 e ln preservadas',()=>{near(run('calc1-derivacao',{f:'log(x)',x:'2'}).primary,1/(2*Math.log(10)));near(run('calc1-derivacao',{f:'ln(x)',x:'2'}).primary,.5);});
test('Regra da cadeia',()=>near(run('calc1-derivacao',{f:'sin(x^2)',x:'1'}).primary,2*Math.cos(1)));
test('Derivação de ordem superior',()=>near(run('calc1-derivacao',{f:'x^4',n:'3',x:'2'}).primary,48));
test('Derivação implícita e taxas relacionadas',()=>{near(run('calc1-implicitas').primary,-.75);near(run('calc1-taxas').primary,-1.5);});
test('Taylor de x³ é exato no grau três',()=>{const r=run('calc1-taylor',{f:'x^3',c:'2',n:'3',x:'-1'});near(r.primary,-1);near(val(r,'Erro absoluto observado'),0);});
test('Newton converge para sqrt(2)',()=>near(run('calc1-newton').primary,Math.SQRT2));
test('Primitiva: derivada devolve integrando',()=>{const r=run('calc2-primitivas',{f:'x*sin(x)'}),s=val(r,'Primitiva F(x) + C').replace(/ \+ C$/,'');const df=K.expr(K.diff(s));[.2,1,2].forEach(x=>near(df(x),x*Math.sin(x)));});
test('Substituição conserva integral',()=>{const r=run('calc2-substituicao');near(r.primary,Math.exp(4)-Math.exp(1));near(val(r,'Integral direta de referência'),r.primary);});
test('Partes: integral x exp(x) de 0 a 1',()=>near(run('calc2-partes').primary,1));
test('Quadratura de seno',()=>near(run('calc2-quadratura',{f:'sin(x)',a:'0',b:'pi'}).primary,2));
test('Impróprias: fronteiras analíticas p=1',()=>{assert.equal(val(run('calc2-improprias',{mode:'p-tail',p:'1'}),'Classificação'),'Divergente');near(run('calc2-improprias',{mode:'p-edge',p:'.5'}).primary,2);});
test('Área entre x e x²',()=>near(run('calc2-areas').primary,1/6));
test('Cascas: integral de 2πx(1−x²)',()=>near(run('calc2-cascas').primary,Math.PI/2));
test('Arco retilíneo e superfície cônica',()=>{const r=run('calc2-arcos',{f:'3*x'});near(r.primary,Math.sqrt(10));near(val(r,'Área de revolução em torno de x'),3*Math.PI*Math.sqrt(10));});
test('Curva circular: comprimento e área',()=>{const r=run('calc2-parametricas-medidas');near(r.primary,2*Math.PI);near(val(r,'½∫(x dy − y dx)'),Math.PI);});
test('RK4 y′=y com y(0)=1',()=>near(run('calc2-edo').primary,Math.exp(2),1e-6));
test('Série geométrica e alternada',()=>{near(val(run('calc2-criterios',{r:'.5'}),'Soma da série'),2);assert.equal(val(run('calc2-criterios',{type:'alternating',p:'.5'}),'Classificação'),'Convergente condicionalmente');});
test('Logaritmo por série no extremo x=1',()=>{const r=run('calc2-series-potencias',{type:'log',x:'1',n:'80'});assert.equal(val(r,'Ponto dentro do intervalo'),'Sim');near(r.primary,Math.log(2),.01);});
test('Hessiana classifica ponto de sela',()=>assert.equal(val(run('calc2-parciais',{f:'x^2-y^2'}),'Classificação'),'Ponto de sela'));
test('Derivada direcional normaliza vetor',()=>near(run('calc2-direcionais').primary,4.4));
test('Integral dupla triangular',()=>near(run('calc2-duplas').primary,1/3));
test('Integral polar inclui jacobiano',()=>near(run('calc2-polares').primary,4*Math.PI));
test('Integral tripla no tetraedro',()=>near(run('calc2-triplas').primary,1/6));
test('Mudança de variáveis: quarto de disco raio dois',()=>near(run('calc2-jacobiano').primary,Math.PI));
test('Lagrange obtém candidato com resíduo pequeno',()=>{const r=run('calc2-lagrange');near(val(r,'Resíduo do sistema'),0);near(val(r,'Objetivo no candidato'),.5);});
test('Divergência e rotacional conhecidos',()=>{const r=run('calc2-campos');near(val(r,'Divergência no ponto'),1);assert.equal(val(r,'Rotacional no ponto'),'0; 0; 2');});
test('Integral de linha em círculo orientado',()=>near(run('calc2-integral-linha').primary,2*Math.PI));
test('Fluxo vertical através de gráfico sobre quadrado',()=>near(run('calc2-fluxo-superficie').primary,1));
for(const [name,id,p] of [
 ['divisão por zero','fund-fracoes',{b:'0',op:'/'}],['variável não autorizada','calc1-derivacao',{f:'x+q'}],['unidades incompatíveis','fund-unidades',{from:'kg',to:'m'}],['triângulo impossível','fund-triangulos',{a:'1',b:'1',c:'3'}],['vetor nulo direcional','calc2-direcionais',{v:'0;0'}],['matriz singular','alg-matrizes',{a:'1;2\n2;4',op:'inverse'}],['normal nula','geo-reta-plano',{n:'0;0;0'}],['denominador implícito nulo','calc1-implicitas',{x:'5',y:'0'}],['Simpson ímpar','calc2-quadratura',{n:'3'}],['polo interior','calc2-quadratura',{f:'1/x',a:'-1',b:'1'}],['densidade negativa','calc2-aplicacoes',{mode:'mass',f:'-1'}],['limites duplos invertidos','calc2-duplas',{lower:'2',upper:'1'}],['entrada como JavaScript','fund-expressoes',{e:'alert(1)'}]
])test('Rejeita '+name,()=>assert.throws(()=>run(id,p)));
const failures=report.filter(r=>!r.ok);console.log(JSON.stringify({total:report.length,passed:report.length-failures.length,failures},null,2));if(process.argv.includes('--report'))fs.writeFileSync(path.join(root,'tests','mathematics-results.json'),JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;
