(function(g){'use strict';
const modules=[],M=g.MathEngine;
const fail=m=>{throw new Error(m);},finite=(x,label='Valor')=>Number.isFinite(x)?x:fail(`${label} não é real e finito. Verifique o domínio.`);
const fmt=x=>typeof x==='number'?(Number.isFinite(x)?Number(x.toPrecision(10)).toLocaleString('pt-BR',{maximumSignificantDigits:10}):String(x)):String(x);
function ast(s,vars=['x']){if(String(s).length>320)fail('Use até 320 caracteres por expressão.');const a=M.parse(s);let count=0;function visit(n){if(++count>220)fail('Expressão muito extensa.');if(n.type==='variable'&&!vars.includes(n.name))fail(`Variável ${n.name} não permitida. Use ${vars.join(', ')||'somente números'}.`);if(n.type==='calculus')fail('Use o módulo específico para operações de cálculo.');if(n.type==='binary'&&!['+','-','*','/','^','%'].includes(n.op))fail('Digite uma expressão, sem igualdade ou comparação.');for(const k of ['left','right','argument','value'])if(n[k]&&typeof n[k]==='object')visit(n[k]);}visit(a);return a;}
function expr(s,vars=['x']){ast(s,vars);const c=M.compile(s);return (...a)=>c(Object.fromEntries(vars.map((v,i)=>[v,a[i]])));}
const num=s=>finite(expr(String(s),[])());
const integer=(s,min=0,max=10000)=>{const n=num(s);if(!Number.isSafeInteger(n)||n<min||n>max)fail(`Informe inteiro entre ${min} e ${max}.`);return n;};
const positive=s=>{const n=num(s);if(n<=0)fail('A medida deve ser positiva.');return n;};
const list=(s,min=1,max=500)=>{const a=String(s).trim().split(/[;\n]+/).map(t=>num(t.trim()));if(a.length<min||a.length>max)fail(`Use entre ${min} e ${max} valores separados por ;.`);return a;};
const vector=(s,dim)=>{const a=list(s,2,3);if(dim&&a.length!==dim)fail(`Use ${dim} componentes separadas por ;.`);return a;};
const matrix=s=>{const a=String(s).trim().split('\n').filter(x=>x.trim()).map(r=>list(r,1,8));if(!a.length||a.length>8||a.some(r=>r.length!==a[0].length))fail('Matriz retangular: até 8 × 8; colunas com ; e linhas com Enter.');return a;};
const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),norm=a=>Math.hypot(...a),add=(a,b)=>a.map((x,i)=>x+b[i]),scale=(a,k)=>a.map(x=>x*k),sub=(a,b)=>add(a,scale(b,-1));
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],transpose=a=>a[0].map((_,j)=>a.map(r=>r[j]));
const multiply=(a,b)=>{if(a[0].length!==b.length)fail('Dimensões incompatíveis.');return a.map(r=>transpose(b).map(c=>dot(r,c)));},identity=n=>Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>+(i===j)));
function rref(raw,cols=raw[0].length){const a=raw.map(r=>r.slice()),pivots=[];let row=0;const tol=1e-11*Math.max(1,...a.map(r=>Math.max(...r.slice(0,cols).map(Math.abs))));for(let j=0;j<cols&&row<a.length;j++){let k=row;for(let i=row+1;i<a.length;i++)if(Math.abs(a[i][j])>Math.abs(a[k][j]))k=i;if(Math.abs(a[k][j])<=tol)continue;[a[row],a[k]]=[a[k],a[row]];const p=a[row][j];a[row]=a[row].map(x=>x/p);for(let i=0;i<a.length;i++)if(i!==row){const t=a[i][j];a[i]=a[i].map((x,h)=>x-t*a[row][h]);}pivots.push(j);row++;}return {a:a.map(r=>r.map(x=>Math.abs(x)<1e-12?0:x)),pivots,rank:row,tol};}
function det(a){if(a.length!==a[0].length)fail('Use matriz quadrada.');const b=a.map(r=>r.slice());let d=1;for(let j=0;j<b.length;j++){let k=j;for(let i=j+1;i<b.length;i++)if(Math.abs(b[i][j])>Math.abs(b[k][j]))k=i;if(b[k][j]===0)return 0;if(k!==j){[b[k],b[j]]=[b[j],b[k]];d=-d;}const p=b[j][j];d*=p;for(let i=j+1;i<b.length;i++){const t=b[i][j]/p;for(let h=j+1;h<b.length;h++)b[i][h]-=t*b[j][h];}}return finite(d);}
function inverse(a){if(a.length!==a[0].length)fail('Use matriz quadrada.');const r=rref(a.map((v,i)=>v.concat(identity(a.length)[i])),a.length);if(r.rank<a.length)fail('Matriz singular na tolerância numérica.');return r.a.map(v=>v.slice(a.length));}
function casInput(s,vars=['x']){function emit(n){if(n.type==='number')return String(n.value);if(n.type==='constant')return n.name==='tau'?'(2*pi)':n.name==='phi'?'((1+sqrt(5))/2)':n.name;if(n.type==='variable')return n.name;if(n.type==='group')return `(${emit(n.value)})`;if(n.type==='unary')return `(${n.op}${emit(n.argument)})`;if(n.type==='binary'){if(n.op==='%')fail('Resto não suportado nesta operação simbólica.');return `(${emit(n.left)}${n.op}${emit(n.right)})`;}if(n.type==='factorial')return `factorial(${emit(n.argument)})`;if(n.type==='call'){const x=emit(n.argument);if(n.name==='cbrt')fail('Na operação simbólica, use potências com domínio especificado.');return n.name==='ln'?`log(${x})`:n.name==='log'?`(log(${x})/log(10))`:n.name==='log2'?`(log(${x})/log(2))`:`${n.name}(${x})`;}fail('Expressão simbólica não suportada.');}return emit(ast(s,vars));}
function symbolic(s,op='simplify',v='x',n=1,vars=['x']){const input=casInput(s,vars);let e=g.nerdamer(input);if(op==='diff')for(let i=0;i<n;i++)e=g.nerdamer.diff(e,v);else if(op==='integrate')e=g.nerdamer.integrate(e,v);else if(op==='expand')e=g.nerdamer.expand(e);else if(op==='factor')e=g.nerdamer.factor(e);else if(op==='partfrac')e=g.nerdamer(`partfrac(${input},${v})`);else e=g.nerdamer(`simplify(${input})`);const out=e.toString();if(/integrate\(|diff\(/.test(out))fail('O motor simbólico não encontrou forma fechada. Tente o módulo numérico.');return out.replace(/\blog\(/g,'ln(');}
const diff=(s,v='x',n=1,vars=['x'])=>symbolic(s,'diff',v,n,vars);
function integral(f,a,b,tol=1e-7){if(a===b)return {value:0,error:0,evaluations:0};if(a>b){const r=integral(f,b,a,tol);return {...r,value:-r.value};}let count=0,error=0;const f0=x=>{if(++count>50000)fail('Limite de amostras atingido. Divida o intervalo.');return finite(f(x),'Integrando');};const fa=f0(a),fb=f0(b),m=(a+b)/2,fm=f0(m),s=(b-a)*(fa+4*fm+fb)/6;function rec(a,b,fa,fm,fb,s,eps,depth){const m=(a+b)/2,l=f0((a+m)/2),r=f0((m+b)/2),sl=(m-a)*(fa+4*l+fm)/6,sr=(b-m)*(fm+4*r+fb)/6,e=Math.abs(sl+sr-s)/15;if(e<=eps){error+=e;return sl+sr+(sl+sr-s)/15;}if(depth<=0)fail('Quadratura não estabilizada. Verifique singularidades ou reduza o intervalo.');return rec(a,m,fa,l,fm,sl,eps/2,depth-1)+rec(m,b,fm,r,fb,sr,eps/2,depth-1);}return {value:finite(rec(a,b,fa,fm,fb,s,tol,18)),error,evaluations:count};}
function sample(f,a,b,n=180){return Array.from({length:n+1},(_,i)=>{const x=a+(b-a)*i/n;let y;try{y=f(x);}catch{y=NaN;}return [x,Number.isFinite(y)?y:null];});}
const series=(name,points,kind='line')=>({name,points,kind}),graph=(...series)=>({series}),curve=(name,f,a,b)=>series(name,sample(f,a,b));
function bounds(p,a='a',b='b'){const x=num(p[a]),y=num(p[b]);if(x>=y)fail('Início deve ser menor que fim.');return [x,y];}
function roots(f,a,b,n=600){const found=[];const put=x=>{if(Number.isFinite(x)&&Math.abs(f(x))<1e-6&&!found.some(r=>Math.abs(r-x)<1e-5))found.push(x);};let x=a,y=f(a);put(a);for(let i=1;i<=n;i++){const t=a+(b-a)*i/n,z=f(t);if(Number.isFinite(y)&&Number.isFinite(z)&&y*z<0){let l=x,r=t,fl=y;for(let k=0;k<55;k++){const m=(l+r)/2,v=f(m);if(!Number.isFinite(v))break;if(fl*v<=0)r=m;else{l=m;fl=v;}}put((l+r)/2);}if(Math.abs(z)<1e-8)put(t);x=t;y=z;}return found.sort((a,b)=>a-b);}
function result(metrics,extras={}){return {metrics:metrics.map(([label,value])=>({label,value:typeof value==='number'?finite(value,label):String(value)})),method:'Cálculo numérico em precisão dupla.',...extras};}
const table=(a,labels)=>({columns:labels||a[0]?.map((_,i)=>String(i+1))||[],rows:a}),field=(key,label,value,type='text',options)=>({key,label,value:String(value),type,options}),select=(key,label,options,value)=>field(key,label,value||options[0][0],'select',options);
function register(area,id,title,group,summary,fields,compute){modules.push({areaId:area,id,title,group,summary,fields,compute,kind:'workbench',focus:group,icon:area==='calculo-2'?'∫':area==='calculo-1'?'d':area==='algebra-vetorial'?'→':area==='geometria'?'◯':'x'});}
function run(id,p){const m=modules.find(m=>m.id===id);if(!m)fail('Laboratório desconhecido.');const values=Object.fromEntries(m.fields.map(f=>{const v=String(p[f.key]??f.value);if(v.length>4000)fail('Entrada muito extensa.');if(f.type==='select'&&!f.options.some(o=>o[0]===v))fail('Opção inválida.');return [f.key,v];}));const r=m.compute(values);if(!r||!Array.isArray(r.metrics))fail('Resultado inválido.');return r;}
g.LabKit={modules,register,field,select,run,fail,finite,fmt,ast,expr,num,integer,positive,list,vector,matrix,dot,norm,add,scale,sub,cross,transpose,multiply,identity,rref,det,inverse,casInput,symbolic,diff,integral,sample,series,graph,curve,bounds,roots,result,table};
})(window);
