(function(g){'use strict';
const K=g.LabKit,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),clone=v=>JSON.parse(JSON.stringify(v)),$=id=>document.getElementById(id),KEY='orbisvWorkbenchV1';
let active=null,worker=null,timer=null,saveTimer=null,inputs={};
try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}');for(const m of K.modules)if(saved[m.id])inputs[m.id]=cleanValues(m,saved[m.id]);}catch{}
function cleanValues(m,raw){if(!raw||typeof raw!=='object')throw new Error('Dados de laboratório inválidos.');return Object.fromEntries(m.fields.map(f=>{const v=String(raw[f.key]??f.value);if(v.length>4000)throw new Error('Entrada muito extensa.');if(f.type==='select'&&!f.options.some(o=>o[0]===v))throw new Error('Opção inválida no registro.');return [f.key,v];}));}
function values(){return Object.fromEntries(active.lab.fields.map(f=>[f.key,$('wb-'+f.key).value]));}
function save(){if(!active)return;inputs[active.lab.id]=values();try{localStorage.setItem(KEY,JSON.stringify(inputs));$('wbSaveStatus').textContent='Entradas salvas neste dispositivo.';}catch{$('wbSaveStatus').textContent='Sem espaço para salvar entradas. Exporte o resultado ou registre no Caderno.';}}
function stop(){clearTimeout(timer);if(worker){worker.terminate();worker=null;}if($('wbCancel'))$('wbCancel').hidden=true;if($('wbCalculate'))$('wbCalculate').disabled=false;}
function close(){if(active){clearTimeout(saveTimer);save();}stop();active=null;}
function field(f,v){return `<label class="wb-field" for="wb-${esc(f.key)}"><span>${esc(f.label)}</span>${f.type==='select'?`<select id="wb-${esc(f.key)}" name="${esc(f.key)}">${f.options.map(([value,label])=>`<option value="${esc(value)}" ${value===v?'selected':''}>${esc(label)}</option>`).join('')}</select>`:f.type==='textarea'?`<textarea id="wb-${esc(f.key)}" name="${esc(f.key)}" rows="4" maxlength="4000" spellcheck="false">${esc(v)}</textarea>`:`<input id="wb-${esc(f.key)}" name="${esc(f.key)}" value="${esc(v)}" maxlength="4000" autocomplete="off" spellcheck="false">`}</label>`;}
function mount(id,node){close();const lab=g.OrbisCatalog.labs[id],v=inputs[id]||cleanValues(lab,{});active={lab,result:null,values:null,revealed:false,yaw:-35,pitch:25};node.innerHTML=`<div class="platform-breadcrumb"><button data-platform-area="${lab.areaId}" type="button">${esc(lab.areaTitle)}</button><span>/</span><span>${esc(lab.group)}</span></div><section class="platform-catalog-head"><div><span class="platform-kicker">LABORATÓRIO</span><h1>${esc(lab.title)}</h1><p>${esc(lab.summary)}</p></div><button class="platform-secondary" data-platform-page="notebook" type="button">Caderno</button></section><div class="wb-layout"><section class="wb-input-panel"><div class="wb-panel-head"><h2>Defina sua atividade</h2><button class="platform-link" type="button" id="wbReset">Restaurar exemplo</button></div><form id="wbForm">${lab.fields.map(f=>field(f,v[f.key])).join('')}<div class="wb-syntax">Use ; para separar valores. Aceita vírgula decimal, pi, sqrt(x), sen(x), ln(x) e log(x) na base 10.</div><label class="wb-practice-toggle"><input type="checkbox" id="wbPractice"> Treinar antes de ver os resultados</label><div class="platform-actions"><button class="platform-primary" id="wbCalculate" type="submit">Calcular e visualizar</button><button class="platform-secondary" id="wbCancel" type="button" hidden>Cancelar</button></div><p id="wbSaveStatus" class="wb-save-status" role="status">Entradas independentes para cada laboratório.</p></form></section><section class="wb-output-panel" aria-label="Resultados"><div id="wbStatus" role="status" aria-live="polite"></div><div id="wbOutput"><div class="wb-empty"><span aria-hidden="true">∴</span><h2>Prepare seu experimento</h2><p>Altere os dados e use “Calcular e visualizar”. Você poderá comparar resultados e registrar a atividade no Caderno.</p></div></div></section></div>`;
$('wbForm').addEventListener('submit',e=>{e.preventDefault();calculate();});$('wbForm').addEventListener('input',e=>{if(!e.target.name)return;stop();active.result=null;active.revealed=false;$('wbOutput').innerHTML='<p class="wb-empty-small">Dados alterados. Calcule novamente para atualizar o resultado.</p>';$('wbStatus').textContent='';clearTimeout(saveTimer);saveTimer=setTimeout(save,200);});$('wbCancel').onclick=()=>{stop();$('wbStatus').textContent='Cálculo cancelado.';};$('wbReset').onclick=()=>{stop();for(const f of lab.fields)$('wb-'+f.key).value=f.value;active.result=null;$('wbOutput').innerHTML='<p class="wb-empty-small">Exemplo restaurado. Calcule para visualizar.</p>';$('wbStatus').textContent='';save();};
}
function calculate(){stop();save();active.result=null;active.attempt=null;active.values=values();$('wbStatus').className='wb-status';$('wbStatus').textContent='Calculando…';$('wbOutput').innerHTML='';$('wbCalculate').disabled=true;$('wbCancel').hidden=false;try{const url=URL.createObjectURL(new Blob([g.OrbisWorkerSource],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);timer=setTimeout(()=>{stop();$('wbStatus').className='wb-status error';$('wbStatus').textContent='O cálculo atingiu 12 segundos. Simplifique a expressão ou divida o intervalo.';},12000);worker.onmessage=e=>{stop();if(!active)return;if(!e.data.ok){$('wbStatus').className='wb-status error';$('wbStatus').textContent=e.data.error;return;}active.result=e.data.result;active.revealed=false;$('wbStatus').textContent='Cálculo concluído.';if($('wbPractice').checked)practice();else reveal();};worker.onerror=()=>{stop();$('wbStatus').className='wb-status error';$('wbStatus').textContent='Não foi possível iniciar o cálculo. Verifique se o navegador permite processamento local por Web Workers.';};worker.postMessage({id:active.lab.id,values:active.values});}catch(e){stop();$('wbStatus').textContent=e.message;}}
function practice(){const metrics=active.result.metrics.filter(m=>typeof m.value==='number'&&Number.isFinite(m.value));if(!metrics.length){$('wbOutput').innerHTML='<div class="wb-practice"><h2>Registre sua previsão</h2><label for="wbHypothesis">Sua resposta ou hipótese</label><textarea id="wbHypothesis" rows="4" maxlength="4000"></textarea><p>Este resultado é simbólico ou textual. A comparação será feita por você após a revelação.</p><button class="platform-primary" id="wbReveal" type="button">Revelar resultado</button></div>';}else{$('wbOutput').innerHTML=`<div class="wb-practice"><span class="platform-kicker">TREINO</span><h2>Qual resultado você espera?</h2><label for="wbTarget">Grandeza a conferir</label><select id="wbTarget">${metrics.map((m,i)=>`<option value="${i}">${esc(m.label)}</option>`).join('')}</select><label for="wbGuess">Sua resposta numérica</label><input id="wbGuess" autocomplete="off" placeholder="Ex.: 2/3 ou 0,6667"><p>Tolerância: 0,01% × máx(1, |resultado|).</p><div class="platform-actions"><button class="platform-primary" id="wbCheck" type="button">Conferir resposta</button><button class="platform-secondary" id="wbReveal" type="button">Revelar resultado</button></div><p id="wbFeedback" role="status"></p></div>`;$('wbCheck').onclick=()=>{try{const target=metrics[Number($('wbTarget').value)],guess=K.num($('wbGuess').value),ok=Math.abs(guess-target.value)<=1e-4*Math.max(1,Math.abs(target.value));active.attempt={label:target.label,answer:$('wbGuess').value,correct:ok};$('wbFeedback').textContent=ok?'Resposta dentro da tolerância.':'Ainda não coincide. Revise o cálculo ou revele o resultado.';}catch(e){$('wbFeedback').textContent=e.message;}};}$('wbReveal').onclick=()=>{if($('wbHypothesis'))active.attempt={label:'Hipótese',answer:$('wbHypothesis').value};reveal();};}
function tableHtml(r,limit=120){if(!r.columns?.length)return '';return `<div class="wb-table-wrap" tabindex="0" aria-label="Tabela de resultados"><table><thead><tr>${r.columns.map(c=>`<th scope="col">${esc(c)}</th>`).join('')}</tr></thead><tbody>${(r.rows||[]).slice(0,limit).map(row=>`<tr>${row.map(v=>`<td>${esc(K.fmt(v))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${r.rows.length>limit?`<p class="wb-method">Mostrando ${limit} de ${r.rows.length} linhas. O CSV contém a tabela completa.</p>`:''}`;}
function reveal(){active.revealed=true;const r=active.result;$('wbOutput').innerHTML=`<div class="wb-result-head"><h2>Resultados</h2><span class="wb-result-tag">${r.plot?.dimensions===3?'VISUALIZAÇÃO 3D':'EXPERIMENTO'}</span></div><dl class="wb-metrics">${r.metrics.map(m=>`<div><dt>${esc(m.label)}</dt><dd>${esc(K.fmt(m.value))}</dd></div>`).join('')}</dl>${r.plot?`<div class="wb-chart-card"><div id="wbPlot"></div>${r.plot.dimensions===3?'<div class="wb-rotation"><label>Rotação <input id="wbYaw" type="range" min="-180" max="180" value="-35"></label><label>Inclinação <input id="wbPitch" type="range" min="-80" max="80" value="25"></label></div>':''}<div id="wbLegend" class="wb-legend"></div></div>`:''}${tableHtml(r)}<p class="wb-method">${esc(r.method||'')}</p>${r.notice?`<p class="wb-notice">${esc(r.notice)}</p>`:''}<div class="wb-result-actions"><button class="platform-primary" type="button" id="wbRecord">Registrar no Caderno</button><button class="platform-secondary" type="button" id="wbJson">Exportar resultado</button>${r.rows?.length||r.plot?'<button class="platform-secondary" type="button" id="wbCsv">Exportar CSV</button>':''}${r.plot?'<button class="platform-secondary" type="button" id="wbSvg">Exportar gráfico SVG</button>':''}</div>`;
if(r.plot){drawPlot();for(const id of ['wbYaw','wbPitch'])if($(id))$(id).oninput=()=>{active.yaw=Number($('wbYaw').value);active.pitch=Number($('wbPitch').value);drawPlot();};$('wbSvg').onclick=()=>download($('wbPlot').innerHTML,'image/svg+xml',`${active.lab.id}.svg`);}
$('wbRecord').onclick=()=>{const snap=snapshot();g.OrbisPlatform.recordCalculation(snap,active.attempt?`${active.attempt.label}: ${active.attempt.answer}${typeof active.attempt.correct==='boolean'?`\nConferência: ${active.attempt.correct?'dentro':'fora'} da tolerância.`:''}`:'');};$('wbJson').onclick=()=>download(JSON.stringify({format:'orbisv-calculation',version:1,snapshot:snapshot()},null,2),'application/json',`${active.lab.id}.json`);if($('wbCsv'))$('wbCsv').onclick=exportCsv;
}
function snapshot(){return {kind:'calculation',labId:active.lab.id,labTitle:active.lab.title,savedAt:new Date().toISOString(),values:clone(active.values),result:clone(active.result)};}
function download(text,mime,name){g.OrbisVRuntime.AppUI.download(text,mime,name);}
function exportCsv(){const r=active.result,rows=r.rows?.length?[r.columns,...r.rows]:[['Série','x','y','z'],...r.plot.series.flatMap(s=>s.points.map(p=>[s.name,...p]))],cell=v=>{let s=typeof v==='number'?String(v).replace('.',','):String(v??'');if(typeof v!=='number'&&/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};download('\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8',`${active.lab.id}.csv`);}
function drawPlot(){const plot=active.result.plot,is3=plot.dimensions===3,yaw=active.yaw*Math.PI/180,pitch=active.pitch*Math.PI/180,project=p=>{if(!Array.isArray(p)||p.slice(0,is3?3:2).some(x=>typeof x!=='number'||!Number.isFinite(x)))return null;return is3?[p[0]*Math.cos(yaw)-p[1]*Math.sin(yaw),(p[0]*Math.sin(yaw)+p[1]*Math.cos(yaw))*Math.sin(pitch)+p[2]*Math.cos(pitch)]:p;};
const series=plot.series.map(s=>({...s,points:s.points.map(project)})),points=series.flatMap(s=>s.points.filter(Boolean));if(!points.length){$('wbPlot').innerHTML='<p>Nenhum ponto real finito no intervalo.</p>';return;}let xmin=Math.min(...points.map(p=>p[0]),0),xmax=Math.max(...points.map(p=>p[0]),0),ymin=Math.min(...points.map(p=>p[1]),0),ymax=Math.max(...points.map(p=>p[1]),0);if(xmax===xmin){xmin-=1;xmax+=1;}if(ymax===ymin){ymin-=1;ymax+=1;}let dx=xmax-xmin,dy=ymax-ymin;xmin-=dx*.08;xmax+=dx*.08;ymin-=dy*.1;ymax+=dy*.1;const W=760,H=440,left=66,top=24,pw=W-left-26,ph=H-top-50;if(plot.equal){const scale=Math.max((xmax-xmin)/pw,(ymax-ymin)/ph),cx=(xmax+xmin)/2,cy=(ymax+ymin)/2;xmin=cx-scale*pw/2;xmax=cx+scale*pw/2;ymin=cy-scale*ph/2;ymax=cy+scale*ph/2;}
const px=x=>left+(x-xmin)/(xmax-xmin)*pw,py=y=>top+ph-(y-ymin)/(ymax-ymin)*ph,styles=getComputedStyle(document.documentElement),color=v=>styles.getPropertyValue(v).trim(),ink=color('--text')||'#17293e',muted=color('--muted')||'#64748b',bg=color('--surface')||'#fff',line=color('--line')||'#cbd5e1',colors=[color('--cyan'),color('--pink'),color('--violet'),color('--green'),'#b98b3a'].map((c,i)=>c||['#167b9d','#c24980','#7554cc','#25826b','#b98b3a'][i]);
const groupNames=[...new Set(series.map(s=>s.name))];
let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(active.lab.title)}"><title>${esc(active.lab.title)}</title><rect width="${W}" height="${H}" fill="${esc(bg)}"/><defs><clipPath id="wbClip"><rect x="${left}" y="${top}" width="${pw}" height="${ph}"/></clipPath></defs>`;
if(!is3){for(let i=0;i<=5;i++){const x=xmin+(xmax-xmin)*i/5,y=ymin+(ymax-ymin)*i/5;svg+=`<path d="M${px(x)} ${top}V${top+ph} M${left} ${py(y)}H${left+pw}" stroke="${esc(line)}" fill="none"/><text x="${px(x)}" y="${H-20}" text-anchor="middle" font-size="12" fill="${esc(muted)}">${esc(K.fmt(Number(x.toPrecision(3))))}</text><text x="${left-8}" y="${py(y)+4}" text-anchor="end" font-size="12" fill="${esc(muted)}">${esc(K.fmt(Number(y.toPrecision(3))))}</text>`;}svg+=`<path d="M${px(0)} ${top}V${top+ph} M${left} ${py(0)}H${left+pw}" stroke="${esc(muted)}" stroke-width="1.2" fill="none"/>`;}
svg+='<g clip-path="url(#wbClip)">';series.forEach((s,i)=>{const idx=groupNames.indexOf(s.name),ci=colors[idx%colors.length],dash=idx%3===1?'8 3':idx%3===2?'2 3':'';if(s.kind==='points'){s.points.filter(Boolean).slice(0,3000).forEach(p=>{svg+=`<circle cx="${px(p[0])}" cy="${py(p[1])}" r="3.5" fill="${esc(ci)}"/>`;});}else{let path='',prev=null;for(const p of s.points){if(!p){prev=null;continue;}const split=prev&&!plot.equal&&Math.abs(p[1]-prev[1])>(ymax-ymin)*.55;path+=`${!prev||split?'M':'L'}${px(p[0]).toFixed(2)} ${py(p[1]).toFixed(2)} `;prev=p;}svg+=`<path d="${path}" stroke="${esc(ci)}" fill="none" stroke-width="2" stroke-dasharray="${dash}"/>`;}});svg+='</g>';
if(is3){const base=project([0,0,0]),ext=Math.max(...plot.series.flatMap(s=>s.points.flat().filter(v=>typeof v==='number'&&Number.isFinite(v)).map(Math.abs)),1)*.65;for(let i=0;i<3;i++){const q=[0,0,0];q[i]=ext;const end=project(q);svg+=`<path d="M${px(base[0])} ${py(base[1])}L${px(end[0])} ${py(end[1])}" stroke="${esc(muted)}" stroke-dasharray="3 4"/><text x="${px(end[0])+5}" y="${py(end[1])-5}" font-size="14" fill="${esc(ink)}">${['x','y','z'][i]}</text>`;}}
svg+='</svg>';$('wbPlot').innerHTML=svg;const seen=new Set();$('wbLegend').innerHTML=series.map((s,i)=>{if(seen.has(s.name))return '';seen.add(s.name);return `<span><i style="background:${esc(colors[groupNames.indexOf(s.name)%colors.length])}"></i>${esc(s.name)}</span>`;}).join('');
}
function validateSnapshot(raw){const lab=g.OrbisCatalog.labs[raw?.labId];if(!lab||lab.kind!=='workbench')throw new Error('Laboratório do registro não reconhecido.');const cell=v=>{if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v==='string'&&v.length<=5000)return v;throw new Error('Valor inválido no registro.');};const r=raw.result;if(!r||!Array.isArray(r.metrics)||r.metrics.length>60)throw new Error('Resultado inválido no Caderno.');const result={metrics:r.metrics.map(m=>({label:String(m.label).slice(0,200),value:cell(m.value)})),method:String(r.method||'').slice(0,3000),notice:String(r.notice||'').slice(0,3000)};if(r.columns){if(!Array.isArray(r.columns)||r.columns.length>20||!Array.isArray(r.rows)||r.rows.length>5000)throw new Error('Tabela inválida no registro.');result.columns=r.columns.map(cell);result.rows=r.rows.map(row=>{if(!Array.isArray(row)||row.length!==r.columns.length)throw new Error('Linha inválida.');return row.map(cell);});}if(r.plot){if(!Array.isArray(r.plot.series)||r.plot.series.length>120)throw new Error('Gráfico inválido.');let count=0;result.plot={dimensions:r.plot.dimensions===3?3:2,equal:!!r.plot.equal,series:r.plot.series.map(s=>{if(!Array.isArray(s.points)||(count+=s.points.length)>15000)throw new Error('Gráfico excede o limite.');return {name:String(s.name).slice(0,200),kind:s.kind==='points'?'points':'line',points:s.points.map(p=>{if(!Array.isArray(p)||p.length<2||p.length>3||p.some(x=>x!==null&&(typeof x!=='number'||!Number.isFinite(x))))throw new Error('Coordenada inválida.');return p;})};})};}return {kind:'calculation',labId:lab.id,labTitle:lab.title,savedAt:Number.isFinite(Date.parse(raw.savedAt))?raw.savedAt:new Date().toISOString(),values:cleanValues(lab,raw.values),result};}
function snapshotHtml(raw){const s=raw,r=s.result,lab=g.OrbisCatalog.labs[s.labId];return `<section class="platform-snapshot"><strong>Experimento registrado · ${esc(s.labTitle)}</strong><span>${esc(new Date(s.savedAt).toLocaleString('pt-BR'))}</span><details><summary>Consultar entradas e resultados</summary><dl class="wb-note-data">${lab.fields.map(f=>`<div><dt>${esc(f.label)}</dt><dd>${esc(s.values[f.key])}</dd></div>`).join('')}${r.metrics.map(m=>`<div><dt>${esc(m.label)}</dt><dd>${esc(K.fmt(m.value))}</dd></div>`).join('')}</dl><p>${esc(r.method)}</p>${r.notice?`<p>${esc(r.notice)}</p>`:''}${tableHtml(r,30)}</details><button class="platform-secondary" type="button" data-note-restore>Reabrir experimento</button></section>`;}
function restore(s){const valid=validateSnapshot(s);inputs[s.labId]=valid.values;g.OrbisPlatform.openLab(s.labId);}
g.addEventListener('pagehide',()=>{clearTimeout(saveTimer);save();});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save();});
g.OrbisWorkbench={mount,close,validateSnapshot,snapshotHtml,restore,calculate,tableHtml};
})(window);
